---
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    if: |
      github.actor != 'tina-cloud-app[bot]' && 
      !contains(github.event.head_commit.message, 'feat: update content with tinacms')
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: betania-ingolstadt-website
